export type {
  IPage,
  IPageRequest,
  IPageNav,
  IPageContributor,
  IPageFollowed,
  IEditPageContent,
  IPageTableOfContentsHeading,
  IPageTableOfContents,
  IShareLink,
  IPageShare,
  IFoundPageContent,
  IExportPDF,
  IPageStatistic,
} from 'infostack-shared/common/interfaces';
