export type {
  IPage,
  IPageRequest,
  IPageNav,
  IPageContributor,
  IPageFollowed,
  IEditPageContent,
  IPageContent,
  IPageContentWithAuthor,
  IPageTableOfContents,
  IPageTableOfContentsHeading,
  IShareLink,
  IPageShare,
  IFoundPageContent,
  IExportPDF,
  IPageRecent,
  IPageRequested,
  IPageStatistic,
} from 'infostack-shared';
