ls:
  .dir: regex:([.a-z]*)([-.][a-z]+)*
  .scss: regex:([.a-z]*)([-.][a-z]+)*
  .ts: regex:([.a-z\d]*)([-.][a-z\d]+)*

ignore:
  - node_modules
  - build
  - shared/build
  - shared/node_modules
  - frontend/build
  - frontend/node_modules
  - backend/build
  - backend/node_modules
  - backend/src/data/migrations
  - mobile/ios
  - mobile/android
  - mobile/node_modules
  - .git
  - .husky
