enum HttpErrorMessage {
  NO_SUCH_EMAIL = 'That address is either invalid or is not associated with a user account',
  EMAIL_ALREADY_EXISTS = 'User with such email already exists',
  INTERNAL_SERVER_ERROR = 'Internal Server Error',
  INVALID_TOKEN = 'Invalid token',
  NO_SUCH_PARENT_COMMENT = 'No parent comment with such id',
  UNAUTHORIZED = 'Unauthorized',
  NO_WORKSPACE_WITH_SUCH_ID = 'Workspace with such id does not exist',
  WORKSPACE_ALREADY_EXISTS = 'Workspace with such title already exists',
  NO_WORKSPACE_ACCESS = 'You have no access to this workspace',
  TAG_EMPTY_NAME = 'Empty tag name is not allowed',
  SKILL_EMPTY_NAME = 'Empty skill name is not allowed',
  TAG_IN_WORKSPACE_ALREADY_EXISTS = 'Duplicate workspace tag',
  SKILL_IN_WORKSPACE_ALREADY_EXISTS = 'Duplicate workspace skill',
  TAG_IN_WORKSPACE_NOT_FOUND = 'Tag not found in workspace',
  SKILL_IN_WORKSPACE_NOT_FOUND = 'Skill not found in workspace',
  TEAM_NAME_ALREADY_EXISTS = 'Team with such name already exists',
  TEAM_EMPTY_STRING = 'Team with empty string is not allowed',
  TEAM_OWNER_ID = 'UserId is required to change Team owner',
  DELETED_FROM_WORKSPACE = 'You were deleted from this workspace',
  NO_EMAIL = 'You should have publics GitHub email to login',
  NO_PAGE_WITH_SUCH_ID = 'No page with such id',
  INVALID_LOGIN_DATA = 'Incorrect email or password',
  INVALID_FILE_TYPE = 'Invalid file type',
}

export { HttpErrorMessage };
